apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: sonthh98/user-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: USER_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: USER_POSTGRES_USERNAME
            - name: USER_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: USER_POSTGRES_PASSWORD
            - name: USER_POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: USER_POSTGRES_DATABASE
