apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
spec:
  destination:
    name: gke_son-devops_asia-southeast1_son-devops
    namespace: dev
  source:
    path: deployment/api-gateway/overlays/dev
    repoURL: https://github.com/sonthh/devops.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-api
spec:
  destination:
    name: gke_son-devops_asia-southeast1_son-devops
    namespace: dev
  source:
    path: deployment/user-api/overlays/dev
    repoURL: https://github.com/sonthh/devops.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
